# function to check the CSV files generated by data loader for errors

function CheckErrorFile {

    Param ([string]$perrorfilepath)

    $csvlines = (Get-Content $perrorfilepath | Measure-Object -line).Lines
    
    # header is always 1 row so we look for > 1 rows
    if ($csvlines -gt 1)
    {
        $errorCount = $csvLines - 1
        $errorMessage = [string]::Format("** errors ** {0} failed rows in {1}", $errorCount, $perrorfilepath)
        # this will print red error message but not stop execution
        write-error $errorMessage
		
		# Send-MailMessage -From $From -to $To -Subject $Subject -Body $Body -SmtpServer $SMTPServer  -Attachments $Attachment 
    }
 

}



